### ISSUE TITLE
error: cannot find symbol class FilenameUtils

### ISSUE THREAD

**Issue by zakblacki** [Breta01/docus#11]
After updating dependancies and upgrading gradle 
I got this error FilenameUtils any fix?

**Comment by Breta01** [comment]
How did you update the dependencies? Does this error happens during build?

It should be this library: [https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FilenameUtils.html](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FilenameUtils.html)
Please let me know if you find a solution.

**Comment by zakblacki** [comment]
File -> Project Structure -> Suggestions Update 
Apparently this is the one causing issue so I just reversed to the previous version it's working thanks, 
"commons-io:commons-io:2.6"

**Comment by zakblacki** [comment]
Is it possible to lower minSdkVersion 19 ? my phone isn't compatible with 21 but I'm guessing It won't work with the library used

**Comment by Breta01** [comment]
It is due to the CameraX library. Supporting cameras on older Sdk is much more work.

**Comment by zakblacki** [comment]
Alright, we could use a share button for social media and gallery option 
Do you plan adding feature MRZ reading for Passeport or ID card extraction ?

**Comment by Breta01** [comment]
Currently the app implements only this: [https://bretahajek.com/2017/01/scanning-documents-photos-opencv/](https://bretahajek.com/2017/01/scanning-documents-photos-opencv/)

I am planning adding different scanning modes, but it is work in progress.

**Comment by zakblacki** [comment]
Would be nice if you could make another article on android explaining the steps instead python

**Comment by Breta01** [comment]
Maybe I will, but I is basically the same only using OpenCV Java API instead of Python. Only tricky part is getting images from live preview in YUV format and extracting Y channel (grayscale). The page detection algorithm is than in [https://github.com/Breta01/docus/blob/master/app/src/main/java/com/bretahajek/docus/ocr/PageDetector.java](https://github.com/Breta01/docus/blob/master/app/src/main/java/com/bretahajek/docus/ocr/PageDetector.java). I thing if you look through it you will find it quite similar to the python version.
